baseUrl = "https://www.hewei.in/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "岁月留痕"
theme = "zozo"
hasCJKLanguage = true # has chinese/japanese/korean
paginate = 8          # shows the number of articles
enableEmoji = true

pygmentsUseClasses = true
pygmentCodeFences = true

[author]
  name = "何伟"

[params]
  enableSummary = true  # display the article summary
  
[social]
  github = "https://github.com/Dream4ever"

[params.valine]
  enable = true
  appId = "6kGh7JpRLb89n7mDsx4LmntN-gzGzoHsz"
  appKey = "kWKa5LtKrMR1sMPfRl5Wzx4r"
  visitor = true
  requiredFields = ['nick','mail']